import {
    CommandPermissionLevel,
    CustomCommandParamType,
    CustomCommandStatus,
    Player,
    system,
    type CustomCommandOrigin,
    type CustomCommandResult,
    type StartupEvent,
} from "@minecraft/server";
import { Context } from "../../context.js";
import { Audio, playCompiledAudioCue } from "../../audio.js";
import type { AudioCompiledCue } from "../../audio/compiled.js";
import {
    compileAudioTextWithVisuals,
    type AudioVisualPack,
    type AudioTextCompilationWithVisuals,
    type AudioVisualCue,
} from "../../audio/definitions.js";
import {
    formatAudioActionBar,
    type AudioActionBarOptions,
    audioVisualizationDurationTicks,
} from "./visualizer.js";

export type AudioPlayerCommandLogger = {
    error(message?: unknown, ...optionalParams: unknown[]): void;
};

export type AudioPlayerCommandInstallOptions = {
    /**
     * Command namespace used for the audio command.
     *
     * Defaults to `"bebe"` for direct use. Project tooling should pass the
     * project namespace so dev commands share one Bedrock command namespace.
     */
    readonly commandNamespace?: string;
    /**
     * Permission level used for the custom command.
     *
     * Defaults to `GameDirectors`. Tooling may lower this in development-only
     * pipelines where the command is not packaged.
     */
    readonly commandPermissionLevel?: CommandPermissionLevel;
    /**
     * Logger used for unexpected playback failures after the command callback
     * has yielded out of Bedrock's restricted execution phase.
     */
    readonly logger?: AudioPlayerCommandLogger;
    /**
     * Greys note/chord cells that have already passed in the command actionbar.
     *
     * Defaults to `true` for the injected development command. Pass `false`
     * from code to keep past notes coloured by pitch.
     */
    readonly greyPastNotes?: boolean;
    /**
     * Optional dev-only source visual metadata generated by the project build.
     *
     * Loaded project audio still plays from the compact `Audio` pack; this pack
     * is only used by the injected development command's action bar.
     */
    readonly visualPack?: AudioVisualPack;
};

export type AudioPlayerCommandParseResult =
    | { readonly kind: "list" }
    | { readonly kind: "play"; readonly cueId: string }
    | { readonly kind: "text"; readonly source: string }
    | { readonly ok: false; readonly message: string };

/**
 * Parses `/namespace:audio` arguments.
 *
 * Supported forms are `list`, `play <cueId>`, shorthand `<cueId>`, and
 * `text <baud>`.
 */
export function parseAudioPlayerCommand(
    args: readonly unknown[],
): AudioPlayerCommandParseResult {
    const actionOrCue = typeof args[0] === "string" ? args[0].trim() : "";
    const cueOrText = typeof args[1] === "string" ? args[1].trim() : "";
    if (!actionOrCue) {
        return usageError();
    }

    if (actionOrCue === "list") {
        return { kind: "list" };
    }

    if (actionOrCue === "play") {
        return cueOrText ? { kind: "play", cueId: cueOrText } : usageError();
    }

    if (actionOrCue === "text") {
        return cueOrText ? { kind: "text", source: cueOrText } : usageError();
    }

    return { kind: "play", cueId: actionOrCue };
}

/**
 * Installs the internal dev-time BAUD audio player command.
 *
 * This entry point is intended for `blr` injection. Gameplay projects should
 * use the root `Audio` service directly.
 */
export function installAudioPlayerCommand(
    options: AudioPlayerCommandInstallOptions = {},
): () => void {
    const commandContext = new Context();
    const commandNamespace = normalizeCommandNamespace(
        options.commandNamespace ?? "bebe",
    );
    const visualCues = createAudioVisualCueMap(options.visualPack);
    const actionBarOptions: AudioActionBarOptions = {
        greyPastNotes: options.greyPastNotes ?? true,
    };
    const startupCallback = (event: StartupEvent) => {
        event.customCommandRegistry.registerCommand(
            {
                name: `${commandNamespace}:audio`,
                description: "Play Bebe audio in a dev world.",
                permissionLevel:
                    options.commandPermissionLevel ??
                    CommandPermissionLevel.GameDirectors,
                cheatsRequired: true,
                mandatoryParameters: [
                    {
                        name: "actionOrCue",
                        type: CustomCommandParamType.String,
                    },
                ],
                optionalParameters: [
                    {
                        name: "cueOrText",
                        type: CustomCommandParamType.String,
                    },
                ],
            },
            (origin, ...args) =>
                handleAudioPlayerCommand(
                    commandContext,
                    origin,
                    args,
                    options.logger,
                    visualCues,
                    actionBarOptions,
                ),
        );
    };

    system.beforeEvents.startup.subscribe(startupCallback);

    return () => {
        system.beforeEvents.startup.unsubscribe(startupCallback);
        commandContext.dispose();
    };
}

function handleAudioPlayerCommand(
    context: Context,
    origin: CustomCommandOrigin,
    args: readonly unknown[],
    logger: AudioPlayerCommandLogger | undefined,
    visualCues: ReadonlyMap<string, AudioVisualCue>,
    actionBarOptions: AudioActionBarOptions,
): CustomCommandResult {
    const player = origin.sourceEntity;
    if (!(player instanceof Player)) {
        return {
            status: CustomCommandStatus.Failure,
            message: "Bebe audio commands must be run by a player.",
        };
    }

    const action = parseAudioPlayerCommand(args);
    if (isAudioPlayerCommandError(action)) {
        return {
            status: CustomCommandStatus.Failure,
            message: action.message,
        };
    }

    if (action.kind === "list") {
        const cueIds = Audio.cues().map((cue) => cue[0]);
        return {
            status: CustomCommandStatus.Success,
            message:
                cueIds.length === 0
                    ? "No BAUD cues are loaded."
                    : `Loaded BAUD cues: ${cueIds.join(", ")}`,
        };
    }

    if (action.kind === "text") {
        return handleAudioTextCommand(
            context,
            player,
            action.source,
            logger,
            actionBarOptions,
        );
    }

    const cue = Audio.get(action.cueId);
    if (!cue) {
        return {
            status: CustomCommandStatus.Failure,
            message: `Unknown audio cue "${action.cueId}".`,
        };
    }

    system.run(() => {
        try {
            startAudioVisualizer(
                context,
                player,
                visualCues.get(action.cueId) ?? cue,
                logger,
                actionBarOptions,
            );
            Audio.play(context, action.cueId, { target: player });
        } catch (error) {
            logger?.error(
                `[Bebe audio] Failed to play BAUD cue "${action.cueId}".`,
                error,
            );
        }
    });

    return {
        status: CustomCommandStatus.Success,
        message: `Playing BAUD cue "${action.cueId}".`,
    };
}

function handleAudioTextCommand(
    context: Context,
    player: Player,
    source: string,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
): CustomCommandResult {
    const compilation = compileAudioCommandText(source);
    if (compilation instanceof Error) {
        return {
            status: CustomCommandStatus.Failure,
            message: compilation.message,
        };
    }

    const { pack, visual } = compilation;
    const cue = pack.c[0];
    const visualCue = visual.cues[0];
    if (
        pack.c.length !== 1 ||
        visual.cues.length !== 1 ||
        cue === undefined ||
        visualCue === undefined
    ) {
        return {
            status: CustomCommandStatus.Failure,
            message: "BAUD text commands must declare exactly one cue.",
        };
    }

    system.run(() => {
        try {
            startAudioVisualizer(
                context,
                player,
                visualCue,
                logger,
                actionBarOptions,
            );
            playCompiledAudioCue(context, cue, pack.s, { target: player });
        } catch (error) {
            logger?.error(
                `[Bebe audio] Failed to play BAUD text cue "${cue[0]}".`,
                error,
            );
        }
    });

    return {
        status: CustomCommandStatus.Success,
        message: `Playing BAUD text cue "${cue[0]}".`,
    };
}

function startAudioVisualizer(
    context: Context,
    player: Player,
    cue: AudioCompiledCue | AudioVisualCue,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
): void {
    const endTick = audioVisualizationDurationTicks(cue);
    const cueId = "id" in cue ? cue.id : cue[0];
    const startTick = system.currentTick;
    let cancel: (() => void) | undefined;
    const update = () => {
        try {
            player.onScreenDisplay.setActionBar(
                formatAudioActionBar(
                    cue,
                    system.currentTick - startTick,
                    actionBarOptions,
                ),
            );
        } catch (error) {
            cancel?.();
            logger?.error(
                `[Bebe audio] Failed to show BAUD visualization for "${cueId}".`,
                error,
            );
        }
    };

    update();
    if (endTick <= 0) {
        return;
    }

    cancel = context.interval(1, () => {
        update();
        if (system.currentTick - startTick >= endTick) {
            cancel?.();
        }
    });
}

function compileAudioCommandText(
    source: string,
): AudioTextCompilationWithVisuals | Error {
    try {
        return compileAudioTextWithVisuals(normalizeAudioCommandText(source), {
            source: "audio/__command__.baud",
        });
    } catch (error) {
        return error instanceof Error ? error : new Error(String(error));
    }
}

function normalizeAudioCommandText(source: string): string {
    return source
        .replace(/\\r\\n/gu, "\n")
        .replace(/\\n/gu, "\n")
        .replace(/\\r/gu, "\n")
        .split(";")
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
        .join("\n");
}

function normalizeCommandNamespace(namespace: string): string {
    const normalized = namespace.trim();
    if (!/^[a-z0-9_]+$/u.test(normalized)) {
        throw new Error(
            "Audio player command namespace must contain only lowercase letters, numbers, and underscores.",
        );
    }

    return normalized;
}

function usageError(): { readonly ok: false; readonly message: string } {
    return {
        ok: false,
        message:
            "Use audio list, audio play <cueId>, audio <cueId>, or audio text <baud>.",
    };
}

function isAudioPlayerCommandError(
    result: AudioPlayerCommandParseResult,
): result is { readonly ok: false; readonly message: string } {
    return "ok" in result;
}

function createAudioVisualCueMap(
    visualPack: AudioVisualPack | undefined,
): ReadonlyMap<string, AudioVisualCue> {
    return new Map(visualPack?.cues.map((cue) => [cue.id, cue]) ?? []);
}
