import {
    CommandPermissionLevel,
    CustomCommandParamType,
    CustomCommandStatus,
    Player,
    system,
    type CustomCommandOrigin,
    type CustomCommandResult,
    type StartupEvent,
} from "@minecraft/server";
import { ActionFormData } from "@minecraft/server-ui";
import { Context } from "../../context.js";
import { Audio, playCompiledAudioCue } from "../../audio.js";
import type { AudioCompiledCue } from "../../audio/compiled.js";
import {
    compileAudioTextWithVisuals,
    type AudioVisualPack,
    type AudioTextCompilationWithVisuals,
    type AudioVisualCue,
} from "../../audio/definitions.js";
import {
    formatAudioActionBar,
    type AudioActionBarOptions,
    audioVisualizationDurationTicks,
} from "./visualizer.js";

export type AudioPlayerCommandLogger = {
    error(message?: unknown, ...optionalParams: unknown[]): void;
};

export type AudioPlayerCommandInstallOptions = {
    /**
     * Command namespace used for the audio command.
     *
     * Defaults to `"bebe"` for direct use. Project tooling should pass the
     * project namespace so dev commands share one Bedrock command namespace.
     */
    readonly commandNamespace?: string;
    /**
     * Permission level used for the custom command.
     *
     * Defaults to `GameDirectors`. Tooling may lower this in development-only
     * pipelines where the command is not packaged.
     */
    readonly commandPermissionLevel?: CommandPermissionLevel;
    /**
     * Logger used for unexpected playback failures after the command callback
     * has yielded out of Bedrock's restricted execution phase.
     */
    readonly logger?: AudioPlayerCommandLogger;
    /**
     * Greys note/chord cells that have already passed in the command actionbar.
     *
     * Defaults to `true` for the injected development command. Pass `false`
     * from code to keep past notes coloured by pitch.
     */
    readonly greyPastNotes?: boolean;
    /**
     * Optional dev-only source visual metadata generated by the project build.
     *
     * Loaded project audio still plays from the compact `Audio` pack; this pack
     * is only used by the injected development command's action bar.
     */
    readonly visualPack?: AudioVisualPack;
};

export type AudioPlayerCommandParseResult =
    | { readonly kind: "menu" }
    | { readonly kind: "list" }
    | { readonly kind: "play"; readonly cueId: string }
    | { readonly kind: "text"; readonly source: string }
    | { readonly ok: false; readonly message: string };

type AudioPlayerCommandPlaybackRegistry = Map<string, Context>;

const AUDIO_PLAYER_COMMAND_ACTIONS = ["list", "play", "text"] as const;

/**
 * Parses `/namespace:audio` arguments.
 *
 * Supported forms are no arguments, `list`, `play <cueId>`, shorthand
 * `<cueId>`, and `text <baud>`.
 */
export function parseAudioPlayerCommand(
    args: readonly unknown[],
): AudioPlayerCommandParseResult {
    const actionOrCue = typeof args[0] === "string" ? args[0].trim() : "";
    const cueOrText = typeof args[1] === "string" ? args[1].trim() : "";
    if (!actionOrCue) {
        return { kind: "menu" };
    }

    if (actionOrCue === "list") {
        return { kind: "list" };
    }

    if (actionOrCue === "play") {
        return cueOrText ? { kind: "play", cueId: cueOrText } : usageError();
    }

    if (actionOrCue === "text") {
        return cueOrText ? { kind: "text", source: cueOrText } : usageError();
    }

    return { kind: "play", cueId: actionOrCue };
}

/**
 * Installs the internal dev-time BAUD audio player command.
 *
 * This entry point is intended for `blr` injection. Gameplay projects should
 * use the root `Audio` service directly.
 */
export function installAudioPlayerCommand(
    options: AudioPlayerCommandInstallOptions = {},
): () => void {
    const commandContext = new Context();
    const commandPlaybacks: AudioPlayerCommandPlaybackRegistry = new Map();
    const commandNamespace = normalizeCommandNamespace(
        options.commandNamespace ?? "bebe",
    );
    const actionEnumName = `${commandNamespace}:audio_action`;
    const visualCues = createAudioVisualCueMap(options.visualPack);
    const actionBarOptions: AudioActionBarOptions = {
        greyPastNotes: options.greyPastNotes ?? true,
    };
    const startupCallback = (event: StartupEvent) => {
        event.customCommandRegistry.registerEnum(
            actionEnumName,
            createAudioPlayerCommandActionEnumValues(),
        );
        event.customCommandRegistry.registerCommand(
            {
                name: `${commandNamespace}:audio`,
                description: "Play Bebe audio in a dev world.",
                permissionLevel:
                    options.commandPermissionLevel ??
                    CommandPermissionLevel.GameDirectors,
                cheatsRequired: true,
                mandatoryParameters: [],
                optionalParameters: [
                    {
                        name: actionEnumName,
                        type: CustomCommandParamType.Enum,
                    },
                    {
                        name: "cueOrText",
                        type: CustomCommandParamType.String,
                    },
                ],
            },
            (origin, ...args) =>
                handleAudioPlayerCommand(
                    commandContext,
                    origin,
                    args,
                    options.logger,
                    visualCues,
                    actionBarOptions,
                    commandPlaybacks,
                ),
        );
    };

    system.beforeEvents.startup.subscribe(startupCallback);

    return () => {
        system.beforeEvents.startup.unsubscribe(startupCallback);
        commandContext.dispose();
    };
}

function createAudioPlayerCommandActionEnumValues(): string[] {
    const values = new Set<string>(AUDIO_PLAYER_COMMAND_ACTIONS);
    for (const [cueId] of Audio.cues()) {
        values.add(cueId);
    }
    return [...values];
}

function handleAudioPlayerCommand(
    context: Context,
    origin: CustomCommandOrigin,
    args: readonly unknown[],
    logger: AudioPlayerCommandLogger | undefined,
    visualCues: ReadonlyMap<string, AudioVisualCue>,
    actionBarOptions: AudioActionBarOptions,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
): CustomCommandResult {
    const player = origin.sourceEntity;
    if (!(player instanceof Player)) {
        return {
            status: CustomCommandStatus.Failure,
            message: "Bebe audio commands must be run by a player.",
        };
    }

    const action = parseAudioPlayerCommand(args);
    if (isAudioPlayerCommandError(action)) {
        return {
            status: CustomCommandStatus.Failure,
            message: action.message,
        };
    }

    if (action.kind === "menu") {
        context.run(() => {
            void showAudioPlayerMenu(
                context,
                player,
                logger,
                visualCues,
                actionBarOptions,
                commandPlaybacks,
            ).catch((error: unknown) => {
                logger?.error(
                    "[Bebe audio] Failed to show BAUD audio menu.",
                    error,
                );
            });
        });
        return {
            status: CustomCommandStatus.Success,
            message: "Opening BAUD audio menu.",
        };
    }

    if (action.kind === "list") {
        const cueIds = Audio.cues().map((cue) => cue[0]);
        return {
            status: CustomCommandStatus.Success,
            message:
                cueIds.length === 0
                    ? "No BAUD cues are loaded."
                    : `Loaded BAUD cues: ${cueIds.join(", ")}`,
        };
    }

    if (action.kind === "text") {
        return handleAudioTextCommand(
            context,
            player,
            action.source,
            logger,
            actionBarOptions,
            commandPlaybacks,
        );
    }

    const cue = Audio.get(action.cueId);
    if (!cue) {
        return {
            status: CustomCommandStatus.Failure,
            message: `Unknown audio cue "${action.cueId}".`,
        };
    }

    scheduleLoadedAudioPlayerCommandPlayback(
        context,
        player,
        action.cueId,
        visualCues.get(action.cueId) ?? cue,
        logger,
        actionBarOptions,
        commandPlaybacks,
    );

    return {
        status: CustomCommandStatus.Success,
        message: `Playing BAUD cue "${action.cueId}".`,
    };
}

async function showAudioPlayerMenu(
    context: Context,
    player: Player,
    logger: AudioPlayerCommandLogger | undefined,
    visualCues: ReadonlyMap<string, AudioVisualCue>,
    actionBarOptions: AudioActionBarOptions,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
): Promise<void> {
    const cues = Audio.cues();
    const hasActivePlayback = commandPlaybacks.has(player.id);
    const form = new ActionFormData().title("BAUD Audio");
    if (cues.length === 0) {
        form.body("No BAUD cues are loaded.");
    }
    if (hasActivePlayback) {
        form.button("Clear");
    }
    for (const cue of cues) {
        form.button(cue[0]);
    }

    const response = await form.show(player);
    if (response.canceled || response.selection === undefined) {
        return;
    }

    if (hasActivePlayback && response.selection === 0) {
        stopAudioPlayerCommandPlayback(commandPlaybacks, player);
        return;
    }

    const cueIndex = hasActivePlayback
        ? response.selection - 1
        : response.selection;
    const cue = cues[cueIndex];
    if (!cue) {
        return;
    }

    scheduleLoadedAudioPlayerCommandPlayback(
        context,
        player,
        cue[0],
        visualCues.get(cue[0]) ?? cue,
        logger,
        actionBarOptions,
        commandPlaybacks,
    );
}

function handleAudioTextCommand(
    context: Context,
    player: Player,
    source: string,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
): CustomCommandResult {
    const compilation = compileAudioCommandText(source);
    if (compilation instanceof Error) {
        return {
            status: CustomCommandStatus.Failure,
            message: compilation.message,
        };
    }

    const { pack, visual } = compilation;
    const cue = pack.c[0];
    const visualCue = visual.cues[0];
    if (
        pack.c.length !== 1 ||
        visual.cues.length !== 1 ||
        cue === undefined ||
        visualCue === undefined
    ) {
        return {
            status: CustomCommandStatus.Failure,
            message: "BAUD text commands must declare exactly one cue.",
        };
    }

    scheduleCompiledAudioPlayerCommandPlayback(
        context,
        player,
        cue,
        pack.s,
        visualCue,
        logger,
        actionBarOptions,
        commandPlaybacks,
    );

    return {
        status: CustomCommandStatus.Success,
        message: `Playing BAUD text cue "${cue[0]}".`,
    };
}

function scheduleLoadedAudioPlayerCommandPlayback(
    context: Context,
    player: Player,
    cueId: string,
    visualCue: AudioCompiledCue | AudioVisualCue,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
): void {
    const playbackContext = replaceAudioPlayerCommandPlayback(
        context,
        commandPlaybacks,
        player,
    );
    playbackContext.run(() => {
        try {
            startAudioVisualizer(
                playbackContext,
                player,
                visualCue,
                logger,
                actionBarOptions,
            );
            Audio.play(playbackContext, cueId, { target: player });
            clearAudioPlayerCommandPlaybackAfterCue(
                playbackContext,
                commandPlaybacks,
                player,
                visualCue,
            );
        } catch (error) {
            playbackContext.dispose();
            logger?.error(
                `[Bebe audio] Failed to play BAUD cue "${cueId}".`,
                error,
            );
        }
    });
}

function scheduleCompiledAudioPlayerCommandPlayback(
    context: Context,
    player: Player,
    cue: AudioCompiledCue,
    soundIds: readonly string[],
    visualCue: AudioVisualCue,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
): void {
    const playbackContext = replaceAudioPlayerCommandPlayback(
        context,
        commandPlaybacks,
        player,
    );
    playbackContext.run(() => {
        try {
            startAudioVisualizer(
                playbackContext,
                player,
                visualCue,
                logger,
                actionBarOptions,
            );
            playCompiledAudioCue(playbackContext, cue, soundIds, {
                target: player,
            });
            clearAudioPlayerCommandPlaybackAfterCue(
                playbackContext,
                commandPlaybacks,
                player,
                visualCue,
            );
        } catch (error) {
            playbackContext.dispose();
            logger?.error(
                `[Bebe audio] Failed to play BAUD text cue "${cue[0]}".`,
                error,
            );
        }
    });
}

function replaceAudioPlayerCommandPlayback(
    context: Context,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
    player: Player,
): Context {
    stopAudioPlayerCommandPlayback(commandPlaybacks, player, {
        clearActionBar: false,
    });
    const playbackContext = context.createScope();
    commandPlaybacks.set(player.id, playbackContext);
    playbackContext.use(() => {
        if (commandPlaybacks.get(player.id) === playbackContext) {
            commandPlaybacks.delete(player.id);
        }
    });
    return playbackContext;
}

function stopAudioPlayerCommandPlayback(
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
    player: Player,
    options: { readonly clearActionBar?: boolean } = {},
): boolean {
    const playbackContext = commandPlaybacks.get(player.id);
    if (!playbackContext) {
        return false;
    }

    playbackContext.dispose();
    if (options.clearActionBar !== false) {
        player.onScreenDisplay.setActionBar("");
    }
    return true;
}

function clearAudioPlayerCommandPlaybackAfterCue(
    playbackContext: Context,
    commandPlaybacks: AudioPlayerCommandPlaybackRegistry,
    player: Player,
    cue: AudioCompiledCue | AudioVisualCue,
): void {
    const endTick = audioVisualizationDurationTicks(cue);
    playbackContext.timeout(Math.max(1, endTick + 1), () => {
        if (commandPlaybacks.get(player.id) === playbackContext) {
            playbackContext.dispose();
        }
    });
}

function startAudioVisualizer(
    context: Context,
    player: Player,
    cue: AudioCompiledCue | AudioVisualCue,
    logger: AudioPlayerCommandLogger | undefined,
    actionBarOptions: AudioActionBarOptions,
): void {
    const endTick = audioVisualizationDurationTicks(cue);
    const cueId = "id" in cue ? cue.id : cue[0];
    const startTick = system.currentTick;
    let cancel: (() => void) | undefined;
    const update = () => {
        try {
            player.onScreenDisplay.setActionBar(
                formatAudioActionBar(
                    cue,
                    system.currentTick - startTick,
                    actionBarOptions,
                ),
            );
        } catch (error) {
            cancel?.();
            logger?.error(
                `[Bebe audio] Failed to show BAUD visualization for "${cueId}".`,
                error,
            );
        }
    };

    update();
    if (endTick <= 0) {
        return;
    }

    cancel = context.interval(1, () => {
        update();
        if (system.currentTick - startTick >= endTick) {
            cancel?.();
        }
    });
}

function compileAudioCommandText(
    source: string,
): AudioTextCompilationWithVisuals | Error {
    try {
        return compileAudioTextWithVisuals(normalizeAudioCommandText(source), {
            source: "audio/__command__.baud",
        });
    } catch (error) {
        return error instanceof Error ? error : new Error(String(error));
    }
}

function normalizeAudioCommandText(source: string): string {
    return source
        .replace(/\\r\\n/gu, "\n")
        .replace(/\\n/gu, "\n")
        .replace(/\\r/gu, "\n")
        .split(";")
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
        .join("\n");
}

function normalizeCommandNamespace(namespace: string): string {
    const normalized = namespace.trim();
    if (!/^[a-z0-9_]+$/u.test(normalized)) {
        throw new Error(
            "Audio player command namespace must contain only lowercase letters, numbers, and underscores.",
        );
    }

    return normalized;
}

function usageError(): { readonly ok: false; readonly message: string } {
    return {
        ok: false,
        message:
            "Use audio list, audio play <cueId>, audio <cueId>, or audio text <baud>.",
    };
}

function isAudioPlayerCommandError(
    result: AudioPlayerCommandParseResult,
): result is { readonly ok: false; readonly message: string } {
    return "ok" in result;
}

function createAudioVisualCueMap(
    visualPack: AudioVisualPack | undefined,
): ReadonlyMap<string, AudioVisualCue> {
    return new Map(visualPack?.cues.map((cue) => [cue.id, cue]) ?? []);
}
